name: Deploy WordCollectionApi to Render (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-<YOUR-SERVICE-ID>?key=${{ secrets.RENDER_API_KEY }}
